-- Supabase Veritabanı Şeması (Yetmans Barbershop)

-- 1. Services Tablosu
CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    duration_minutes INTEGER DEFAULT 30 NOT NULL
);

-- 2. Gallery Images Tablosu
CREATE TABLE gallery_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Appointments Tablosu
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT REFERENCES services(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    status TEXT DEFAULT 'pending'::text CHECK (status IN ('pending', 'confirmed', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Supabase Storage için 'gallery' adında public bucket oluşturma (Eğer manuel oluşturmak istemezseniz)
INSERT INTO storage.buckets (id, name, public) VALUES ('gallery', 'gallery', true) ON CONFLICT DO NOTHING;

-- Storage için Okuma İzni (Herkes görebilir)
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'gallery');

-- 5. Row Level Security (RLS) Politikaları (Opsiyonel ama önerilir)
-- Varsayılan olarak anonim erişime kapatıp sadece gerekli işlemlere izin verebilirsiniz.
-- Şimdilik Next.js API Routes üzerinden (Server'da) Service Role Key (ya da anon key) kullanacağımız için 
-- tüm tablolara anon için read/write (veya service role için) açabiliriz.
-- VEYA en güvenlisi API route kullanmaktır.

-- Herkesin hizmetleri okuyabilmesi için RLS:
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to services" ON services FOR SELECT USING (true);

-- Herkesin galeri resimlerini okuyabilmesi için RLS:
ALTER TABLE gallery_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to gallery" ON gallery_images FOR SELECT USING (true);

-- Randevuları oluşturabilmeleri için RLS (Anon insert izni):
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert to appointments" ON appointments FOR INSERT WITH CHECK (true);
-- Update ve Select yetkilerini şimdilik sınırlandırıyoruz, Next.js Server (API Route) üzerinden anon yetkisi olmadan / service role key ile veya backend üzerinden okuma yapılacak.
-- Güvenlik sebebiyle herkes başkasının randevusunu göremez.
